AWSTemplateFormatVersion: "2010-09-09"

Parameters: 
  AppName: 
    Type: String
    Default: AppName
    Description: The Name of the App to be Created
  
  TemplatesBucket: 
    Type: String
    Description: Bucket Name for the inner Stack Templates

Resources:

  AuthenticationPool:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Join: 
          - ''
          - - 'https://s3.amazonaws.com/'
            - Ref: TemplatesBucket
            - "/authentication.yml"
      Parameters:
        AppName:
          Ref: AppName
      TimeoutInMinutes: 60

Outputs:
  UserPoolId:
    Value:
      Fn::GetAtt:
        - AuthenticationPool
        - Outputs.UserPoolId
  IdentityPoolId:
    Value:
      Fn::GetAtt:
        - AuthenticationPool
        - Outputs.IdentityPoolId