AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AppName:
    Type: String
    Default: AppName
    Description: The Name of the App to be Created

  StageName:
    Type: String
    Default: "prod"
    Description: The Name of Deployment Stage

  AppRestAPI:
    Type: String
    Description: The RestAPI Id for Deployment

Resources:
  AppRestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description:
        Fn::Join:
          - " "
          - - Ref: AppName
          - - " Deployment Stage"
      RestApiId:
        Ref: AppRestAPI
      StageDescription:
        TracingEnabled: true
      StageName:
        Ref: StageName

Outputs:
  APIUrl:
    Value:
      Fn::Join:
        - ""
        - - "https://"
        - - Ref: AppRestApiId
        - - ".execute-api."
        - - Ref: "AWS::Region"
        - - ".amazonaws.com/"
        - - Ref: StageName
        - - "/"
    Description: "The Endpoint URL of API."

  AppRestAPIRootResource:
    Value:
      Fn::GetAtt:
        - "AppRestApi"
        - "RootResourceId"
    Description: "Application RestAPI Root Resource Id"
