AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AppName:
    Type: String
    Default: AppName
    Description: The Name of the App to be Created

Resources:
  AppRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description:
        Fn::Join:
          - ""
          - - "REST API Endpoint for "
            - Ref: AppName
      EndpointConfiguration: "REGIONAL"
      Name:
        Fn::Join:
          - ""
          - - Ref: AppName
          - - "RESTAPI"

Outputs:
  AppRestAPIReference:
    Value:
      Ref: AppRestApi
    Description: "Application RestAPI definition"

  AppRestAPIRootResource:
    Value:
      Fn::GetAtt:
        - "AppRestApi"
        - "RootResourceId"
    Description: "Application RestAPI Root Resource Id"
